language: go
go:
- 1.14
before_script:
- sed -i -e "s/@DEV@/$TRAVIS_TAG($TRAVIS_COMMIT)/" main.go
- head -n12 main.go | tail -n3
before_install:
- go get github.com/mitchellh/gox
before_deploy:
- gox
deploy:
  provider: releases
  api_key:
    secure: cxZ3aLsLWaeS6nxE0rfzyThz94A7+evJ/IA4R+eglyA0vk9Mz5GtYyodDHiG2xDrQKKHBNNCq3Ge4Bp2V5qS9gpA5AyfZvRoxDOQFP/C0nAnQMKgQyp+98QMqP72jZIFjd5TsGB9pNE7XMqzYtpYP2HyJ22DOAknW8HMZmu221USYW724OFZdCfINK4OTrd1ML3JDxEgw89byZ4J339NrmIFYw16sB0kqTnltDYHP397cvKXVzlkhLmgOqThkrcJiUFIjsTNjLaDsIiUIktSid50I1bWcZZ9z4GV8d82FxlDkZpzwIB4xs+i6Ixis2ncp979OY+soZL19gChNv5R2HqC+K/JXsl0hbyJ0U52wKJVJ+i6ljpoXPUE6Di68jS34z5hBXenL6DOD7/Dh7loVjRCfNdi8l296Adr0OlaCchA5OUaE3yx6tZO3toM3qfq4itYFoSCWZ1/9YOFQydGpMYgsV+cdVMcffnJkdGBmr/bEEnciAhAwrNhxitdYKIJMkcKn/vAW0DYGbcoim6L7ULo6r3WUlSe81LW4cuDmi/iMfvGfSozkr3mHu4ALqLbv538kclO/XrJ1y7yFDyphWKKnN5W7korppVyjH6ZbQb3NQD+hujideQVUknI9pEAREBHzcNpGGCwdBcQ1ZhzbkVoNO1uN5RhFtE9Kz1zHDs=
  file:
    - tableview_windows_386.exe
    - tableview_windows_amd64.exe
    - tableview_linux_386
    - tableview_linux_amd64
    - tableview_linux_arm
    - tableview_darwin_386
    - tableview_darwin_amd64
    - tableview_freebsd_386
    - tableview_freebsd_amd64
    - tableview_freebsd_arm
    - tableview_netbsd_386
    - tableview_netbsd_arm
    - tableview_netbsd_amd64
    - tableview_openbsd_386
    - tableview_openbsd_amd64
  on:
    repo: informationsea/tableview
    tags: 'true'
  skip_cleanup: 'true'
